# Generated by Django 4.2.11 on 2024-03-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soeltravlr', '0003_alter_comment_author_alter_travel_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='travel',
            options={'ordering': ['-travel_date']},
        ),
    ]
