# Generated by Django 4.2.11 on 2024-03-21 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soeltravlr', '0004_alter_comment_options_alter_travel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='like',
            field=models.ManyToManyField(related_name='blog_travel', to=settings.AUTH_USER_MODEL),
        ),
    ]
