# Generated by Django 4.2.11 on 2024-03-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soeltravlr', '0005_travel_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='image',
            field=models.ImageField(default='', upload_to='static/images/'),
        ),
    ]
