# Generated by Django 4.2.11 on 2024-03-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soeltravlr', '0006_travel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_media',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=500),
        ),
    ]
